# Generated by Django 5.0.4 on 2024-04-27 08:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Цена')),
                ('location', models.CharField(max_length=150, unique=True, verbose_name='Местоположение')),
                ('number', models.CharField(max_length=150, unique=True, verbose_name='Номер')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('rooms', models.CharField(max_length=150, unique=True, verbose_name='Количество комнат')),
                ('furnish', models.CharField(max_length=150, unique=True, verbose_name='Мебель')),
                ('status', models.CharField(max_length=150, unique=True, verbose_name='Состояние')),
                ('bedroom', models.CharField(max_length=150, unique=True, verbose_name='Спальня')),
                ('bathroom', models.CharField(max_length=150, unique=True, verbose_name='Ванная')),
                ('balcony', models.CharField(max_length=150, unique=True, verbose_name='Балкон')),
                ('documents', models.CharField(max_length=150, unique=True, verbose_name='Документы')),
                ('age', models.CharField(max_length=150, unique=True, verbose_name='Срок')),
                ('floors', models.CharField(max_length=150, unique=True, verbose_name='Количество этажей')),
                ('square', models.CharField(max_length=150, unique=True, verbose_name='Площадь')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
    ]
