# Generated by Django 5.0.4 on 2024-04-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='age',
            field=models.CharField(max_length=150, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='products',
            name='balcony',
            field=models.CharField(max_length=150, verbose_name='Балкон'),
        ),
        migrations.AlterField(
            model_name='products',
            name='bathroom',
            field=models.CharField(max_length=150, verbose_name='Ванная'),
        ),
        migrations.AlterField(
            model_name='products',
            name='bedroom',
            field=models.CharField(max_length=150, verbose_name='Спальня'),
        ),
        migrations.AlterField(
            model_name='products',
            name='documents',
            field=models.CharField(max_length=150, verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='products',
            name='floors',
            field=models.CharField(max_length=150, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='products',
            name='furnish',
            field=models.CharField(max_length=150, verbose_name='Мебель'),
        ),
        migrations.AlterField(
            model_name='products',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rooms',
            field=models.CharField(max_length=150, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='products',
            name='square',
            field=models.CharField(max_length=150, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(max_length=150, verbose_name='Состояние'),
        ),
    ]
