# Generated by Django 5.0.4 on 2024-04-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_age_alter_products_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='goods_images', verbose_name='Изображение'),
        ),
    ]
