# Generated by Django 5.0.4 on 2024-05-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='age',
        ),
    ]
