# Generated by Django 5.0.4 on 2024-05-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_remove_products_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
